### ISSUE TITLE
ImportError: No module named enum

### ISSUE THREAD

**Issue by matthewbadeau** [andrewmcgr/klipper_tmc_autotune#40]
Received this error when launching for the first time

```python
Unhandled exception during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 175, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 141, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/pi/klipper/klippy/klippy.py", line 121, in load_object
    mod = importlib.import_module('extras.' + module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/pi/klipper/klippy/extras/autotune_tmc.py", line 2, in <module>
    from enum import Enum
ImportError: No module named enum
```

To fix the problem, I ran:

```bash
$ source ~/klippy-env/bin/activate
$ pip install enum
$ deactivate
```

**Comment by Frix-x** [comment]
@andrewmcgr this issue makes me realize that this is a side issue with my latest changes: the enum package is only native in Python3. However, since it has been backported to Python2, it can be installed as matthew did.

**Comment by cottec** [comment]
same issue here...
when I check for the Pythion version I see this, so I dont really understand what's the issue here...
`pi@speeder-pad:~$  python -V
Python 2.7.18
pi@speeder-pad:~$  python3 -V
Python 3.8.10
`
