### ISSUE TITLE
Error after update to latest autotune

### ISSUE THREAD

**Issue by agdtek** [andrewmcgr/klipper_tmc_autotune#60]
Hi guys,
Im getting this error after doing an update to your script

Internal error during connect: No module named enum

this is the log

Unhandled exception during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 175, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 141, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/pi/klipper/klippy/klippy.py", line 121, in load_object
    mod = importlib.import_module('extras.' + module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/pi/klipper/klippy/extras/autotune_tmc.py", line 2, in <module>
    from enum import Enum
ImportError: No module named enum
webhooks client 1969438632: New connection
webhooks client 1969438632: Client info {'program': 'Moonraker', 'version': 'v0.8.0-86-ga7e154f'}
Unable to issue reset command on MCU 'mcu'
Unable to issue reset command on MCU 'rpi'
Unable to issue reset command on MCU 'sb2040'
webhooks client 1969438632: Disconnected
Restarting printer

**Comment by agdtek** [comment]
found solution 
ssh do the following
$ source ~/klippy-env/bin/activate
$ pip install enum
$ deactivate

**Comment by scheini79** [comment]
> $ source ~/klippy-env/bin/activate
> $ pip install enum
> $ deactivate

Thanks so much, that's a big relief for me.

**Comment by Ixian** [comment]
Thanks! Helped me as well.

**Comment by mjonuschat** [comment]
TMC Autotune nowadays requires at least Python 3.3 (preferably 3.9 or newer). As this bug report is for Python 2.7 I'll close it as no longer relevant.
